"""Brain abstract interface and response contracts."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from jarvis.core.types import ToolCall, ToolSpec


@dataclass
class BrainResponse:
    """Output generated by a Brain step."""

    text: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)
    usage: dict[str, int] | None = None

    @property
    def has_tool_calls(self) -> bool:
        """Return True if response contains at least one tool call."""
        return len(self.tool_calls) > 0


class Brain(ABC):
    """Abstract interface for LLM Brain engines."""

    @property
    def supports_images(self) -> bool:
        """Return True if the brain provider and configured model support vision/image inputs."""
        return True

    @property
    def model(self) -> str:
        """Return the configured model identifier."""
        return getattr(self, "_model", "")

    @model.setter
    def model(self, value: str) -> None:
        self._model = value

    @abstractmethod
    def next_step(
        self,
        messages: list[dict[str, Any]],
        tool_specs: list[ToolSpec] | None = None,
    ) -> BrainResponse:
        """Generate the next assistant response or tool calls.

        Args:
            messages: List of message dictionaries representing conversation turns.
            tool_specs: Optional list of available ToolSpecs.

        Returns:
            BrainResponse containing text, tool calls, or both.
        """
        pass
